apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pong
  labels:
    app: ping-pong
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping
        image: 'harbor.corp.local/ingress-test/pong:0.1'
        ports:
        - containerPort: 5000
          name: pong
---
apiVersion: v1
kind: Service
metadata:
  name: pong
  labels:
    app: ping-pong
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: pong